### ISSUE TITLE
SIGSEGV when sending "reconnect" while bridge fails to connect to an offline whatsapp

### ISSUE THREAD

**Issue by frederictobiasc** [mautrix/whatsapp#310]
Environment
[mautrix-whatsapp 1.6](https://aur.archlinux.org/packages/mautrix-whatsapp/)

Steps to reproduce:
Connected Whatsapp assumed
- Turn off your Device running Whatsapp
- Send `reconnect` after the bridge noticed, that the connection cannot be restored
- Send `reconnect` again -> SIGSEGV

Expected result: Dont panic
Current result:

```
Jun 02 08:48:26 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:26] [Portal/[...]@s.whatsapp.net-[...]@s.whatsapp.net/DEBUG] Not handling 3AB49054F86C899>
Jun 02 08:48:26 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:26] [Portal/[...]@s.whatsapp.net-[...]@s.whatsapp.net/DEBUG] Not handling CF2419682C4E6E5>
Jun 02 08:48:43 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:43] [Portal/status@broadcast-[...]@s.whatsapp.net/INFO] Syncing portal for @[...]:mozilla.org
Jun 02 08:48:49 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:49] [Command handler/DEBUG] @[...]:matrix.org sent 'reconnect' in ![...]:matrix.org
Jun 02 08:48:49 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:49] [User/@[...]:matrix.org/Conn/DEBUG] Disconnecting websocket
Jun 02 08:48:49 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:49] [User/@[...]:matrix.org/ERROR] Failed to restore session: connection closed before login finished
Jun 02 08:48:49 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:49] [User/@[...]:matrix.org/Conn/DEBUG] Websocket keepalive loop exiting 0xc00032ebc0
Jun 02 08:48:49 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:49] [User/@[...]:matrix.org/Conn/DEBUG] Websocket read pump exiting 0xc00032ebc0
Jun 02 08:48:49 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:49] [User/@[...]:matrix.org/Conn/DEBUG] Websocket disconnection complete
Jun 02 08:48:49 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:49] [User/@[...]:matrix.org/Conn/DEBUG] Dialing wss://web.whatsapp.com/ws
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:50] [User/@[...]:matrix.org/DEBUG] Disconnecting due to failed session restore...
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]: [Jun  2, 2021 08:48:50] [User/@[...]:matrix.org/Conn/DEBUG] Disconnecting websocket
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x559331e57601]
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]: goroutine 99 [running]:
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]: github.com/Rhymen/go-whatsapp.(*Conn).Disconnect(0xc0000d4360, 0xc0007183b0, 0x1)
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]:         github.com/Rhymen/go-whatsapp@v0.1.0/conn.go:226 +0x81
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]: main.(*User).RestoreSession(0xc00016c750, 0xc0000d4300)
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]:         maunium.net/go/mautrix-whatsapp/user.go:316 +0x36c
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]: main.(*User).Connect(0xc00016c750, 0x0, 0x0)
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]:         maunium.net/go/mautrix-whatsapp/user.go:272 +0x325
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]: created by main.(*Bridge).StartUsers
Jun 02 08:48:50 dankwart.aladinn.eu mautrix-whatsapp[124879]:         maunium.net/go/mautrix-whatsapp/main.go:362 +0xcd
Jun 02 08:48:50 dankwart.aladinn.eu systemd[1]: mautrix-whatsapp.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 02 08:48:50 dankwart.aladinn.eu systemd[1]: mautrix-whatsapp.service: Failed with result 'exit-code'.
Jun 02 08:48:50 dankwart.aladinn.eu systemd[1]: mautrix-whatsapp.service: Consumed 1.322s CPU time.
Jun 02 08:49:20 dankwart.aladinn.eu systemd[1]: mautrix-whatsapp.service: Scheduled restart job, restart counter is at 2.
```

**Comment by tulir** [comment]
Doesn't apply anymore
