### ISSUE TITLE
Panic with `--migrate-db`

### ISSUE THREAD

**Issue by erdnaxeli** [mautrix/whatsapp#335]
Hi,

I tried to migrate from sqlite3 to postgresql following the doc, but I got a SIGSEV error:

```
bash-5.1# su-exec $UID:$GID /usr/bin/mautrix-whatsapp --migrate-db sqlite3 /data/mautrix-whatsapp.db
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0xa75a67]

goroutine 1 [running]:
maunium.net/go/mautrix-whatsapp/database.New(0x7ffd1e6eef15, 0x7, 0x7ffd1e6eef1d, 0x19, 0x0, 0x0, 0x803, 0xdee9a0, 0xc00030c380)
      /builds/tulir/mautrix-whatsapp/database/database.go:53 +0xc7
main.(*Bridge).MigrateDatabase(0xc00030e270)
      /builds/tulir/mautrix-whatsapp/main.go:112 +0x8d
main.(*Bridge).Main(0xc00030e270)
      /builds/tulir/mautrix-whatsapp/main.go:420 +0x4b
main.main()
      /builds/tulir/mautrix-whatsapp/main.go:456 +0x10f
```

I am running this in a container, that's why I use the `su-exec` method like the image's entrypoint does.

**Comment by erdnaxeli** [comment]
I still have a panic error:
```
bash-5.1# mautrix-whatsapp -v
mautrix-whatsapp 0.1.8+dev.d52b012b (Aug 19 2021, 16:33:07)
bash-5.1# cd /data/
bash-5.1# su-exec $UID:$GID /usr/bin/mautrix-whatsapp --migrate-db sqlite3 /data/mautrix-whatsapp.db
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0xa76627]

goroutine 1 [running]:
maunium.net/go/mautrix-whatsapp/database.New(0x7ffee3829f15, 0x7, 0x7ffee3829f1d, 0x19, 0x0, 0x0, 0x803, 0xdf1ae0, 0xc000308700)
        /builds/mautrix/whatsapp/database/database.go:53 +0xc7
main.(*Bridge).MigrateDatabase(0xc0003141a0)
        /builds/mautrix/whatsapp/main.go:112 +0x8d
main.(*Bridge).Main(0xc0003141a0)
        /builds/mautrix/whatsapp/main.go:420 +0x4b
main.main()
        /builds/mautrix/whatsapp/main.go:456 +0x10f
```
