### ISSUE TITLE
DB migration: foreign key constraint "message_chat_jid_chat_receiver_fkey"

### ISSUE THREAD

**Issue by erdnaxeli** [mautrix/whatsapp#337]
Hi,

Trying to running the migration from sqlite3 to postgresql, I got a foreign key error.

```
bash-5.1# mautrix-whatsapp -v
mautrix-whatsapp 0.1.8+dev.b11a6360 (Aug 21 2021, 20:55:31
```

```
bash-5.1# su-exec $UID:$GID /usr/bin/mautrix-whatsapp --migrate-db sqlite3 /data/mautrix-whatsapp.db
[21:24:55 21.08.2021] [Database/Upgrade/INFO] Database currently on v24, latest: v24
[21:24:55 21.08.2021] [Database/Upgrade/INFO] Database currently on v0, latest: v24
[21:24:55 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v1: Initial schema
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v2: Add ON DELETE CASCADE to message table
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v3: Add timestamp column to messages
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v4: Add last_connection column to users
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v5: Update message content to new protocol version. This may take a while.
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v6: Add columns to store custom puppet info
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v7: Add user-portal mapping table
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v8: Add columns to store avatar MXC URIs
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v9: Add columns to store portal in filtering community meta
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v10: Move state store to main DB
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v11: Add columns to store full member info in state store
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v12: Adjust the length of column topic in portal
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v13: Add encryption status to portal table
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v14: Add crypto store to database
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v15: Add outbound group sessions to database
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v16: Add enable_presence column for puppets
[21:24:56 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v17: Add account_id to crypto store
[21:24:57 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v18: Add enable_receipts column for puppets
[21:24:57 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v19: Add megolm withheld data to crypto store
[21:24:57 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v20: Add cross-signing keys to crypto store
[21:24:57 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v21: Add sent column for messages
[21:24:57 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v22: Remove message content from local database
[21:24:57 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v23: Replace VARCHAR(255) with TEXT in the database
[21:24:57 21.08.2021] [Database/Upgrade/INFO] Upgrading database to v24: Replace VARCHAR(255) with TEXT in the crypto database
Migrating portal: found 164 rows of data, migrating in 3 batches: ### -- done with 162 rows inserted
Migrating user: found 31 rows of data, migrating in 1 batches: # -- done with 31 rows inserted
Migrating puppet: found 418 rows of data, migrating in 9 batches: ######### -- done with 410 rows inserted
Migrating user_portal: found 92 rows of data, migrating in 1 batches: # -- done with 92 rows inserted
Migrating message: found 197146 rows of data, migrating in 2701 batches: #####################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################panic: pq: insert or update on table "message" violates foreign key constraint "message_chat_jid_chat_receiver_fkey"

goroutine 1 [running]:
maunium.net/go/mautrix-whatsapp/database.migrateTable(0xc0003a0190, 0xc0003a03c0, 0xe82079, 0x7, 0xc000331ba8, 0x7, 0x7, 0x0, 0x0)
        /builds/mautrix/whatsapp/database/migrate.go:79 +0xe09
maunium.net/go/mautrix-whatsapp/database.Migrate(0xc0003a0190, 0xc0003a03c0)
        /builds/mautrix/whatsapp/database/migrate.go:111 +0x725
main.(*Bridge).MigrateDatabase(0xc00038a270)
        /builds/mautrix/whatsapp/main.go:134 +0x3ac
main.(*Bridge).Main(0xc00038a270)
        /builds/mautrix/whatsapp/main.go:420 +0x4b
main.main()
        /builds/mautrix/whatsapp/main.go:456 +0x10f
```

**Comment by erdnaxeli** [comment]
Weirdly I cannot found the wrong row, I must be doing something wrong:
```
sqlite> select * from message where not exists (select 1 from portal where portal.jid = message.chat_jid and portal.receiver = message.chat_receiver);
sqlite> 
```

**Comment by rreuvekamp** [comment]
I'm affected by this as well. The portal row in question does exist in the sqlite database, but not in postgres.

Using bridge version:

> mautrix-whatsapp 0.2.2 (Dec 29 2021, 17:09:35)

Build with: 

> ./build.sh -tags nocrypto

From the output of the migration it seems not every portal is migrated. 

> Migrating portal: found 319 rows of data, migrating in 7 batches: ####### -- done with 313 rows inserted

You've got the same. You have 164 portal rows, but 162 inserted.

I've been looking into it but I cannot seem to understand why it skips those 6 in my case. I'll do more research some other time.
