### ISSUE TITLE
Panic during DBMS migration: `no such column: jid`

### ISSUE THREAD

**Issue by bnjbvr** [mautrix/whatsapp#386]
Hi! When trying to change the database from sqlite3 to postgres (14), I get the following error:

```
> mautrix-whatsapp --migrate-db sqlite3 /data/db.sqlite
<!-- more upgrading database -->
[20:27:44 09.11.2021] [Database/Upgrade/INFO] Upgrading database to v30: Replace VARCHAR(255) with TEXT in the Matrix state store
Migrating portal: found 112 rows of data, migrating in 2 batches: ## -- done with 111 rows inserted
Migrating user: found 2 rows of data, panic: no such column: jid

goroutine 1 [running]:
maunium.net/go/mautrix-whatsapp/database.Migrate(0xc000332640, 0xc00025ddf0)
        /builds/mautrix/whatsapp/database/migrate.go:101 +0xf4e
main.(*Bridge).MigrateDatabase(0xc000314340)
        /builds/mautrix/whatsapp/main.go:154 +0x2a5
main.(*Bridge).Main(0xc00022e680)
        /builds/mautrix/whatsapp/main.go:433 +0x39
main.main()
        /builds/mautrix/whatsapp/main.go:469 +0x16f
```

The postgres db is empty, and the sqlite3 db i haven't touched myself (so migrations should have been handled by software itself). Am i doing something wrong?

Thanks for all your amazing work <3

**Comment by bnjbvr** [comment]
Looks like the `migrate.go` file hasn't been updated in a while, since it mentions a few columns that don't exist anymore in the upgraded database scheme: e.g. jid has been renamed in `2021-10-21-multidevice-updates.go`. Will see if I can make it work again.
