### ISSUE TITLE
Bridge crashing every time a message is sent

### ISSUE THREAD

**Issue by chagai95** [mautrix/whatsapp#424]
```

Jan 21 10:27:39 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:39] [Matrix/DEBUG] Starting handling of transaction 1230482 (1 EDUs (unstable))
Jan 21 10:27:40 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:40] [Matrix/Bot/WARN] Request #2 failed: HTTP 504, retrying in 4 seconds
Jan 21 10:27:40 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:40] [Puppet/491729652683@s.whatsapp.net/DEBUG] Skipping sync processing: custom user not connected to whatsapp
Jan 21 10:27:40 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:40] [Matrix/@mr:chagai.website/DEBUG] req #27: GET http://matrix-nginx-proxy:12080/_matrix/client/r0/sync?filter=1&set_presence=offline&since=s1617234_14315964_282_913186_133231_762_35492_1345300_1&timeout=30000
Jan 21 10:27:43 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:43] [Matrix/DEBUG] Starting handling of transaction 1230483 (1 EDUs (unstable))
Jan 21 10:27:44 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:44] [Matrix/Bot/DEBUG] req #2: PUT http://matrix-nginx-proxy:12080/_matrix/client/r0/profile/@whatsappbot:chagai.website/avatar_url?user_id=%40whatsappbot%3Achagai.website {"avatar_url":"mxc://maunium.net/NeXNQarUbrlYBiPCpprYsRqr"}
Jan 21 10:27:50 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:50] [Portal/41766524456-1613595628@g.us/DEBUG] Sending read receipts by 41766524456.0:2@s.whatsapp.net (last read: 1642599091, was zero: false, explicit: true): map[]
Jan 21 10:27:53 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:53] [Matrix/DEBUG] Starting handling of transaction 1230484 (1 EDUs (unstable))
Jan 21 10:27:53 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:53] [User/@344722243231krt:matrix.org/Client/Send/DEBUG] <iq id="200.49-5" to="s.whatsapp.net" type="get" xmlns="w:p"><ping/></iq>
Jan 21 10:27:53 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:53] [User/@344722243231krt:matrix.org/Client/Recv/DEBUG] <iq from="s.whatsapp.net" id="200.49-5" t="1642757273" type="result"/>
Jan 21 10:27:54 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:54] [Matrix/DEBUG] Starting handling of transaction 1230485 (1 PDUs)
Jan 21 10:27:54 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:54] [Portal/15152593078-1607258247@g.us/DEBUG] Received event $r-QBaGOD_YpYzNmMutWPizyitemjBBPo835y-pF4Sj4 from @telegram_299986122:chagai.website
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: [Jan 21, 2022 09:27:56] [Portal/15152593078-1607258247@g.us/DEBUG] Sending event $r-QBaGOD_YpYzNmMutWPizyitemjBBPo835y-pF4Sj4 to WhatsApp 1D092A5D8A44DB00E34FB9263E15A731
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x877d6e]
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: goroutine 13637 [running]:
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: go.mau.fi/whatsmeow.(*Client).addRecentMessage(0x0, {{0xc0022c39e0, 0x16}, 0x0, 0x0, {0xc0022c39f7, 0x4}, 0x0}, {0xc0022c3b60, 0x20}, ...)
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: /builds/mautrix/whatsapp/.cache/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220111203410-b078a9e90863/retry.go:41 +0x6e
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: go.mau.fi/whatsmeow.(*Client).SendMessage(0x0, {{0xc0022c39e0, 0x16}, 0x0, 0x0, {0xc0022c39f7, 0x4}, 0x0}, {0xc0022c3b60, 0x20}, ...)
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: /builds/mautrix/whatsapp/.cache/pkg/mod/go.mau.fi/whatsmeow@v0.0.0-20220111203410-b078a9e90863/send.go:58 +0x105
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: main.(*Portal).HandleMatrixMessage(0xc002614a80, 0xc000a52b80, 0xc00246cf00)
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: /builds/mautrix/whatsapp/portal.go:2355 +0x373
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: main.(*Portal).handleMatrixMessageLoopItem(0xc001ea5778, {0xc00246cf00, 0xc000a52b80})
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: /builds/mautrix/whatsapp/portal.go:243 +0x19f
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: main.(*Portal).handleMessageLoop(0xc002614a80)
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: /builds/mautrix/whatsapp/portal.go:257 +0xf1
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: created by main.(*Bridge).NewPortal
Jan 21 10:27:56 localhost.localdomain matrix-mautrix-whatsapp[2615]: /builds/mautrix/whatsapp/portal.go:158 +0x1d1


```

**Comment by chagai95** [comment]
I think this is because I was logged out of WhatsApp on my main device

**Comment by chagai95** [comment]
I logged in again and now it's working. Looks like a WhatsApp problem.
